"""AES-256 (Fernet) symmetric encryption for biometric data and PII at rest.

Used for face embedding vectors (NFR-27) and emergency contact phone
numbers. The key is sourced exclusively from environment configuration —
never hardcoded or stored alongside the data it protects.
"""
import base64
import hashlib

import numpy as np
from cryptography.fernet import Fernet

from app.config import get_settings


def _normalize_key(secret: str) -> bytes:
    """Build a Fernet-compatible key from a configured secret.

    Supports both hexadecimal secrets (legacy behavior) and arbitrary strings
    generated by Render's ``generateValue``.
    """
    secret = secret.strip()
    if not secret:
        raise ValueError("EMBEDDING_ENCRYPTION_KEY must not be empty")

    try:
        raw_key = bytes.fromhex(secret)
    except ValueError:
        raw_key = secret.encode("utf-8")

    if len(raw_key) < 32 or len(raw_key) > 32:
        raw_key = hashlib.sha256(raw_key).digest()

    return base64.urlsafe_b64encode(raw_key)


def _build_fernet() -> Fernet:
    settings = get_settings()
    return Fernet(_normalize_key(settings.EMBEDDING_ENCRYPTION_KEY))


_fernet = None


def get_fernet() -> Fernet:
    global _fernet
    if _fernet is None:
        _fernet = _build_fernet()
    return _fernet


def encrypt_bytes(data: bytes) -> bytes:
    return get_fernet().encrypt(data)


def decrypt_bytes(token: bytes) -> bytes:
    return get_fernet().decrypt(token)


def encrypt_str(value: str) -> str:
    return get_fernet().encrypt(value.encode("utf-8")).decode("utf-8")


def decrypt_str(token: str) -> str:
    return get_fernet().decrypt(token.encode("utf-8")).decode("utf-8")


def encrypt_embedding(embedding: np.ndarray) -> bytes:
    return encrypt_bytes(embedding.astype(np.float32).tobytes())


def decrypt_embedding(encrypted: bytes) -> np.ndarray:
    return np.frombuffer(decrypt_bytes(encrypted), dtype=np.float32)
